name: CI Pipeline

on:
    push:
        branches:
            - main
            - develop_app
            # - ci

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '20'


        -   name: Install backend deps
            run: |
                cd backend
                npm install

        -   name: Build backend
            run: |
                cd backend
                npm run build

        # Frontend
        -   name: Install frontend deps
            run: |
                cd frontend
                npm install

        -   name: Build frontend
            run: |
                cd frontend
                npm run build