name: Docker CI/CD

on:
    push:
        branches:
            - main
            - develop_app
            - ci
            - cd
            - Docker_Deplyment
            - docker_cicd
            - dockerhub

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        # 🔐 Login to Docker Hub
        -   name: Login to Docker Hub
            run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        # 🐳 Build backend image
        -   name: Build Backend
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./backend

        # 🐳 Build frontend image
        -   name: Build Frontend
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend

        # 🚀 Push images
        -   name: Push Backend
            run: docker push ${{ secrets.DOCKER_USERNAME }}/backend

        -   name: Push Frontend
            run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend

        # 🚀 Deploy on EC2
        -   name: Deploy via SSH
            uses: appleboy/ssh-action@v1.0.0
            with:
                host: ${{ secrets.EC2_HOST }}
                username: ubuntu
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    cd /home/ubuntu/project-1

                    sudo docker compose down

                    sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend
                    sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend

                    sudo docker compose up -d